/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as ArenaIndexRouteImport } from './routes/arena.index'
import { Route as ArenaCodeRouteImport } from './routes/arena.$code'
import { Route as AuthenticatedAtividadeIdRouteImport } from './routes/_authenticated/atividade.$id'
import { Route as AuthenticatedSessaoGameIdRouteImport } from './routes/_authenticated/sessao.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArenaIndexRoute = ArenaIndexRouteImport.update({
  id: '/arena/',
  path: '/arena/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaCodeRoute = ArenaCodeRouteImport.update({
  id: '/arena/$code',
  path: '/arena/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtividadeIdRoute =
  AuthenticatedAtividadeIdRouteImport.update({
    id: '/atividade/$id',
    path: '/atividade/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessaoGameIdRoute =
  AuthenticatedSessaoGameIdRouteImport.update({
    id: '/sessao/$gameId',
    path: '/sessao/$gameId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/arena/$code': typeof ArenaCodeRoute
  '/arena/': typeof ArenaIndexRoute
  '/atividade/$id': typeof AuthenticatedAtividadeIdRoute
  '/sessao/$gameId': typeof AuthenticatedSessaoGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/arena/$code': typeof ArenaCodeRoute
  '/arena': typeof ArenaIndexRoute
  '/atividade/$id': typeof AuthenticatedAtividadeIdRoute
  '/sessao/$gameId': typeof AuthenticatedSessaoGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/arena/$code': typeof ArenaCodeRoute
  '/arena/': typeof ArenaIndexRoute
  '/_authenticated/atividade/$id': typeof AuthenticatedAtividadeIdRoute
  '/_authenticated/sessao/$gameId': typeof AuthenticatedSessaoGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/painel'
    | '/arena/$code'
    | '/arena/'
    | '/atividade/$id'
    | '/sessao/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/painel'
    | '/arena/$code'
    | '/arena'
    | '/atividade/$id'
    | '/sessao/$gameId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/painel'
    | '/arena/$code'
    | '/arena/'
    | '/_authenticated/atividade/$id'
    | '/_authenticated/sessao/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ArenaCodeRoute: typeof ArenaCodeRoute
  ArenaIndexRoute: typeof ArenaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/arena/': {
      id: '/arena/'
      path: '/arena'
      fullPath: '/arena/'
      preLoaderRoute: typeof ArenaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/$code': {
      id: '/arena/$code'
      path: '/arena/$code'
      fullPath: '/arena/$code'
      preLoaderRoute: typeof ArenaCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atividade/$id': {
      id: '/_authenticated/atividade/$id'
      path: '/atividade/$id'
      fullPath: '/atividade/$id'
      preLoaderRoute: typeof AuthenticatedAtividadeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessao/$gameId': {
      id: '/_authenticated/sessao/$gameId'
      path: '/sessao/$gameId'
      fullPath: '/sessao/$gameId'
      preLoaderRoute: typeof AuthenticatedSessaoGameIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedAtividadeIdRoute: typeof AuthenticatedAtividadeIdRoute
  AuthenticatedSessaoGameIdRoute: typeof AuthenticatedSessaoGameIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedAtividadeIdRoute: AuthenticatedAtividadeIdRoute,
  AuthenticatedSessaoGameIdRoute: AuthenticatedSessaoGameIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ArenaCodeRoute: ArenaCodeRoute,
  ArenaIndexRoute: ArenaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}